## Data files
geno_fold_size_file = "/home/jeffchen/sfgwas-lmm/data/ukb_fix/party4/foldSizes.txt"

geno_binary_file_prefix = "/home/jeffchen/sfgwas-lmm/data/ukb_fix/party4/fold"
geno_block_size_file = "/home/jeffchen/sfgwas-lmm/data/ukb_fix/party4/blockSizes.txt"
geno_block_to_chrom_file = "/home/jeffchen/sfgwas-lmm/data/ukb_fix/party4/blockToChrom.txt"
geno_count_file = "/home/jeffchen/sfgwas-lmm/data/ukb_fix/party4/ukb_qc_group_bgen_3.gcount.transpose.bin"
snp_position_file = "/home/jeffchen/sfgwas-lmm/data/ukb_fix/party4/pos.txt"

step_2_geno_binary_file_prefix = "/home/jeffchen/sfgwas-lmm/data/ukb_fix/party4/fold"
step_2_geno_block_size_file = "/home/jeffchen/sfgwas-lmm/data/ukb_fix/party4/blockSizes.txt"
step_2_geno_block_to_chrom_file = "/home/jeffchen/sfgwas-lmm/data/ukb_fix/party4/blockToChrom.txt"
step_2_geno_count_file = "/home/jeffchen/sfgwas-lmm/data/ukb_fix/party4/ukb_qc_group_bgen_3.gcount.transpose.bin"
step_2_snp_position_file = "/home/jeffchen/sfgwas-lmm/data/ukb_fix/party4/pos.txt"


pheno_file = "/home/jeffchen/sfgwas-lmm/data/ukb_fix/party4/pheno.txt"
covar_file = "/home/jeffchen/sfgwas-lmm/data/ukb_fix/party4/cov.txt"

## Output and cache paths
output_dir = "out/"
cache_dir = "cache/"

## Computational paramters
local_num_threads = 63
#local_num_threads = 15