num_main_parties = 6
hub_party_id = 1

## Crypto parameters
# Options: PN12QP109, PN13QP218, PN14QP438, PN15QP880, PN16QP1761
# Defined in ckks/params.go in Lattigo library
ckks_params = "PN14QP438"

mpc_num_threads = 126
mpc_objs_per_block = 6
mpc_num_main_threads = 21

#mpc_num_threads = 6
#mpc_objs_per_block = 6
#mpc_num_main_threads = 1

memory_limit = 536870912000
# 120 GB

mpc_field_size = 256
mpc_data_bits = 150
mpc_frac_bits = 50

#calc_g_capacity = 1

calc_g_capacity = 21

## Data dimensions
num_inds = [0,29824,52908,101785,93641,76567,54822]
num_snps = 581927
num_covs = 15
geno_num_blocks = 82
geno_num_folds = 5

step_2_num_snps = 581927
step_2_geno_num_blocks = 82

## Networking parameters
# Party with a smaller ID listens for connection
# Port only needed for the listener

[servers.party0]
ipaddr = "10.150.15.235"
ports  = {party1 = "8020", party2 = "8220", party3 = "8420", party4 = "8620", party5 = "8820", party6 = "9020"}

[servers.party1]
ipaddr = "10.150.15.214"
ports  = {party2 = "9220", party3 = "9420", party4 = "9620", party5 = "9820", party6 = "10020"}

[servers.party2]
ipaddr = "10.150.15.215"
ports  = {party3 = "10220", party4 = "10420", party5 = "10620", party6 = "10820"}

[servers.party3]
ipaddr = "10.150.15.231"
ports  = {party4 = "11020", party5 = "11220", party6 = "11420"}

[servers.party4]
ipaddr = "10.150.15.232"
ports  = {party5 = "11620", party6 = "11820"}

[servers.party5]
ipaddr = "10.150.15.233"
ports  = {party6 = "12020"}

[servers.party6]
ipaddr = "10.150.15.234"
ports  = {}