## Data files: none for party 0

## Output and cache paths
output_dir = "out/"
cache_dir = "cache/"

## Computational paramters
#local_num_threads = 29
local_num_threads = 63


## Data dimensions
geno_fold_size_file = "/home/jeffchen/sfgwas-lmm/data/ukb_fix/party0/foldSizes.txt"
geno_block_size_file = "/home/jeffchen/sfgwas-lmm/data/ukb_fix/party0/blockSizes.txt"
geno_block_to_chrom_file = "/home/jeffchen/sfgwas-lmm/data/ukb_fix/party0/blockToChrom.txt"
geno_count_file = "/home/jeffchen/sfgwas-lmm/data/ukb_fix/party1/ukb_qc_group_bgen_0.gcount.transpose.bin"
snp_position_file = "/home/jeffchen/sfgwas-lmm/data/ukb_fix/party1/pos.txt"

step_2_geno_block_size_file = "/home/jeffchen/sfgwas-lmm/data/ukb_fix/party0/blockSizes.txt"
step_2_geno_block_to_chrom_file = "/home/jeffchen/sfgwas-lmm/data/ukb_fix/party0/blockToChrom.txt"
step_2_geno_count_file = "/home/jeffchen/sfgwas-lmm/data/ukb_fix/party1/ukb_qc_group_bgen_0.gcount.transpose.bin"
step_2_snp_position_file = "/home/jeffchen/sfgwas-lmm/data/ukb_fix/party1/pos.txt"
