## Data files
geno_fold_size_file = "../example_data/party1/foldSizes.txt"

geno_binary_file_prefix = "../example_data/party1/fold"
geno_block_size_file = "../example_data/party1/blockSizes.txt"
geno_block_to_chrom_file = "../example_data/party1/blockToChrom.txt"
geno_count_file = "../example_data/party1/geno/all.gcount.transpose.bin"
snp_position_file = "../example_data/party1/snp_pos.txt"

step_2_geno_binary_file_prefix = "../example_data/party1/fold"
step_2_geno_block_size_file = "../example_data/party1/blockSizes.txt"
step_2_geno_block_to_chrom_file = "../example_data/party1/blockToChrom.txt"
step_2_geno_count_file = "../example_data/party1/geno/all.gcount.transpose.bin"
step_2_snp_position_file = "../example_data/party1/snp_pos.txt"

pheno_file = "../example_data/party1/pheno.txt"
covar_file = "../example_data/party1/cov.txt"

## Output and cache paths
output_dir = "../example_data/out/party1"
cache_dir = "../example_data/cache/party1"

## Computational paramters
local_num_threads = 63
