## Data files: none for party 0

## Output and cache paths
output_dir = "../example_data/out/party0"
cache_dir = "../example_data/cache/party0"

## Computational paramters
local_num_threads = 63

## Data dimensions
geno_fold_size_file = "../example_data/party0/foldSizes.txt"

geno_block_size_file = "../example_data/party0/blockSizes.txt"
geno_block_to_chrom_file = "../example_data/party0/blockToChrom.txt"

step_2_geno_block_size_file = "../example_data/party0/blockSizes.txt"
step_2_geno_block_to_chrom_file = "../example_data/party0/blockToChrom.txt"
