num_main_parties = 2
hub_party_id = 1

## Crypto parameters
# Options: PN12QP109, PN13QP218, PN14QP438, PN15QP880, PN16QP1761
# Defined in ckks/params.go in Lattigo library
ckks_params = "PN14QP438"

mpc_num_threads = 126
mpc_objs_per_block = 6
mpc_num_main_threads = 21

#mpc_num_threads = 6
#mpc_objs_per_block = 6
#mpc_num_main_threads = 1

memory_limit = 120000000000 # 120GB

mpc_field_size = 256
mpc_data_bits = 120
mpc_frac_bits = 40

calc_g_capacity = 6

## Data dimensions
num_inds = [0, 1000, 1000]
num_snps = 100000
num_covs = 5
num_chrs = 22
geno_num_blocks = 22
geno_num_folds = 5

step_2_num_snps = 100000
step_2_geno_num_blocks = 22

## Networking parameters
# Party with a smaller ID listens for connection
# Port only needed for the listener

[servers.party0]
ipaddr = "127.0.0.1"
ports = { party1 = "8020", party2 = "8220" } # Port numbers need to be at least mpc_num_threads apart

[servers.party1]
ipaddr = "127.0.0.1"
ports = { party2 = "8420" }

[servers.party2]
ipaddr = "127.0.0.1"
