## Shared keys
shared_keys_path = "../example_data/keys"

## Data files: none for party 0

## Output and cache paths
output_dir = "../example_data/out/party0"
cache_dir = "../example_data/cache/party0"

## Computational paramters
local_num_threads = 63
