## Data files
geno_fold_size_file = "../example_data/party2/foldSizes.txt"

geno_binary_file_prefix = "../example_data/party2/fold"
geno_block_size_file = "../example_data/party2/blockSizes.txt"
geno_block_to_chrom_file = "../example_data/party2/blockToChrom.txt"
geno_count_file = "../example_data/party2/all.gcount.transpose.bin"
snp_position_file = "../example_data/party2/snp_pos.txt"

step_2_geno_binary_file_prefix = "../example_data/party2/fold"
step_2_geno_block_size_file = "../example_data/party2/blockSizes.txt"
step_2_geno_block_to_chrom_file = "../example_data/party2/blockToChrom.txt"
step_2_geno_count_file = "../example_data/party2/all.gcount.transpose.bin"
step_2_snp_position_file = "../example_data/party2/snp_pos.txt"

pheno_file = "../example_data/party2/pheno.txt"
covar_file = "../example_data/party2/cov.txt"

## Output and cache paths
output_dir = "out/party2"
cache_dir = "cache/party2"

## Computational paramters
local_num_threads = 63
