## Data files: none for party 0

## Output and cache paths
output_dir = "out/party0"
cache_dir = "cache/party0"

## Computational paramters
local_num_threads = 63

## Data dimensions
geno_block_size_file = "../example_data/party0/blockSizes.txt"
geno_block_to_chrom_file = "../example_data/party0/blockToChrom.txt"
snp_position_file = "../example_data/party0/pos.txt"

step_2_geno_block_size_file = "../example_data/party0/blockSizes.txt"
step_2_geno_block_to_chrom_file = "../example_data/party0/blockToChrom.txt"
step_2_snp_position_file = "../example_data/party0/pos.txt"